config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'questions#home'
  get 'ask', to: 'questions#ask'
  get 'about', to: 'questions#about'
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def home
  end

  def ask
  end

  def about
  end

  def answer

    question = params[:question]

    if question == "I am going to work right now!"
      @answer = "Great!"
    elsif question.include?("?")
      @answer = "Silly question, get dressed and go to work!"
    else
      return @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/about.html.erb
<h1>About the Coach</h1>

<h3>The coach has a temper. Be careful when you ask him questions...</h3>

<h4>If the message is I am going to work, the coach will answer "Great!"<br>
If the message has a question mark (?) at the end, the coach will answer "Silly question, get dressed and go to work!".<br>
Otherwise the coach will answer "I don't care, get dressed and go to work!"</h4>
<p><%= link_to "Back to home", root_path %></p>

app/views/questions/answer.html.erb
<h1>The Coach's answer</h1>

<h2>You:</h2>
<%= params[:question] %>

<h2>Coach:</h2>
<%= @answer %>

<h2>Ask another question?</h2>

<form action="/answer" method="get">
  <input type="text" name="question" placeholder="What's your question?">
  <input type="submit" value="Ask!">
</form>

<p><%= link_to "Back to home", root_path %></p>

app/views/questions/ask.html.erb
<h1>Ask the coach a questions!</h1>

<form action="/answer" method="get">
  <input type="text" name="question" placeholder="What's your question?">
  <input type="submit" value="Ask!">
</form>

<!--   Parameters: {"question"=>"hello"}
 -->


<p><%= link_to "Back to home", root_path %></p>

app/views/questions/home.html.erb
<h1>Welcome to Stupid Coach!</h1>

<h2><%= link_to "Ask a question", ask_path %></h2>
<p><%= link_to "About the Coach", about_path %></p>